using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine;

public class SheepMovement : MonoBehaviour
{
    public float movement_speed = 0.5f;

    private GameObject game_controller;
    private List<GameObject> blocks_in_level;
    private GameObject current_block;
    private GameObject current_lane;
    private int current_block_index;

    private void Awake()
    {
        // PlayerInputActions is the c# file generated by the new input system, using the input maps/actions defined in the unity editor
        PlayerInputActions player_input_actions = new PlayerInputActions();

        // Enable the player action map
        player_input_actions.Player.Enable();

        // Subscribe to the performed event of each input action
        player_input_actions.Player.Jump.performed += Jump;
        player_input_actions.Player.MoveLeft.performed += MoveLeft;
        player_input_actions.Player.MoveRight.performed += MoveRight;
    }

    private void Start()
    {
        game_controller = GameObject.Find("Game Controller");
        blocks_in_level = game_controller.GetComponent<LevelData>().GetBlocksInLevel();

        // Start the player off on the first block in their current lane
        current_block_index = 0;
        current_block = blocks_in_level[current_block_index];
        current_lane = current_block.GetComponent<BlockData>().GetLane(PlayerData.curr_lane).gameObject;
    }

    private void Update()
    {
        current_lane = current_block.GetComponent<BlockData>().GetLane(PlayerData.curr_lane).gameObject;
        if (current_block.tag == "Straight")
        {
            Transform start_point = current_lane.transform.Find("Start");
            transform.position = start_point.position;
            transform.rotation = start_point.rotation;
        }
        else if (current_block.tag == "Turn")
        {
            Transform start_point = current_lane.GetComponent<CurveData>().control_points[0];
            transform.position = start_point.position;
            transform.rotation = start_point.rotation;
        }
    }

    private void Jump(InputAction.CallbackContext context)
    {
        print("Jump");
    }

    private void MoveLeft(InputAction.CallbackContext context)
    {
        //print("Move left");
        switch (PlayerData.curr_lane)
        {
            case PlayerData.Lanes.LEFT:
                // Do nothing
                break;
            case PlayerData.Lanes.MIDDLE:
                PlayerData.curr_lane = PlayerData.Lanes.LEFT;
                break;
            case PlayerData.Lanes.RIGHT:
                PlayerData.curr_lane = PlayerData.Lanes.MIDDLE;
                break;
        }
    }

    private void MoveRight(InputAction.CallbackContext context)
    {
        //print("Move right");
        switch (PlayerData.curr_lane)
        {
            case PlayerData.Lanes.LEFT:
                PlayerData.curr_lane = PlayerData.Lanes.MIDDLE;
                break;
            case PlayerData.Lanes.MIDDLE:
                PlayerData.curr_lane = PlayerData.Lanes.RIGHT;
                break;
            case PlayerData.Lanes.RIGHT:
                // Do nothing
                break;
        }
    }
}
